-- Create database if not exists
CREATE DATABASE IF NOT EXISTS alx_book_store;

-- Use the database
USE alx_book_store;

-- Create tables
CREATE TABLE BOOKS (
  BOOK_ID INT PRIMARY KEY,
  TITLE VARCHAR(255),
  AUTHOR_ID INT,
  PRICE DECIMAL(10, 2),
  PUBLICATION_DATE DATE
);

CREATE TABLE AUTHORS (
  AUTHOR_ID INT PRIMARY KEY,
  FIRST_NAME VARCHAR(100),
  LAST_NAME VARCHAR(100),
  BIOGRAPHY TEXT
);

CREATE TABLE CUSTOMERS (
  CUSTOMER_ID INT PRIMARY KEY,
  FIRST_NAME VARCHAR(100),
  LAST_NAME VARCHAR(100),
  EMAIL VARCHAR(255),
  PHONE VARCHAR(20),
  ADDRESS VARCHAR(255)
);

CREATE TABLE ORDERS (
  ORDER_ID INT PRIMARY KEY,
  CUSTOMER_ID INT,
  ORDER_DATE DATE,
  TOTAL DECIMAL(10, 2),
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

CREATE TABLE ORDER_DETAILS (
  ORDER_ID INT,
  BOOK_ID INT,
  QUANTITY INT,
  PRICE DECIMAL(10, 2),
  PRIMARY KEY (ORDER_ID, BOOK_ID),
  FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
  FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID)
);
